# Generated by Django 5.1.2 on 2024-10-29 17:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Course title', max_length=80)),
                ('description', models.TextField(help_text='Course description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Course price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.PositiveSmallIntegerField(help_text='Course duration in weeks')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Achievement name', max_length=50)),
                ('description', models.TextField(help_text='Achievement description')),
                ('score', models.PositiveSmallIntegerField(help_text='Achievement score')),
                ('course', models.ForeignKey(help_text='Course associated with the achievement', on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='course.course')),
            ],
        ),
    ]
