# Generated by Django 5.1.2 on 2024-10-29 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('user_course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(help_text='Course associated with the user', on_delete=django.db.models.deletion.PROTECT, related_name='user_courses', to='course.course'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(help_text='User associated with the course', on_delete=django.db.models.deletion.PROTECT, related_name='user_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
