# Generated by Django 5.1.2 on 2024-10-29 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('user_course', '0003_alter_usercourse_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(help_text='Achievement associated with the user', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='course.achievement')),
                ('user', models.ForeignKey(help_text='User achievements', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
