# Generated by Django 5.1.2 on 2024-10-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0001_initial'),
        ('user_course', '0004_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(help_text='Achievements of the user', related_name='users', through='user_course.UserAchievement', to='course.achievement'),
        ),
    ]
