# Generated by Django 5.1.2 on 2024-10-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0003_user_balance'),
        ('user_course', '0004_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(help_text='Courses taken by the user', related_name='users', through='user_course.UserCourse', to='course.course'),
        ),
    ]
