# Generated by Django 5.1.2 on 2024-10-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField(default=False, help_text='Is lesson free?')),
                ('ordering_number', models.PositiveSmallIntegerField(help_text='Lesson ordering number in course')),
                ('title', models.CharField(help_text='Content title', max_length=80)),
                ('course', models.ForeignKey(help_text='Course associated with the content', on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Content text')),
                ('document', models.FileField(help_text='Content document', upload_to='documents/')),
                ('lesson', models.ForeignKey(help_text='Lesson associated with the quiz', on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='course_lesson.lesson')),
            ],
        ),
    ]
